/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWorkforceRouteImport } from './routes/_app/workforce'
import { Route as AppTimeRouteImport } from './routes/_app/time'
import { Route as AppTalentRouteImport } from './routes/_app/talent'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPostingsRouteImport } from './routes/_app/postings'
import { Route as AppPayrollRouteImport } from './routes/_app/payroll'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppOrgRouteImport } from './routes/_app/org'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppMonitoringRouteImport } from './routes/_app/monitoring'
import { Route as AppLeaveRouteImport } from './routes/_app/leave'
import { Route as AppImportExportRouteImport } from './routes/_app/import-export'
import { Route as AppHiringRouteImport } from './routes/_app/hiring'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppEngagementRouteImport } from './routes/_app/engagement'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppAttritionRouteImport } from './routes/_app/attrition'
import { Route as AppAttendanceRouteImport } from './routes/_app/attendance'
import { Route as AppAlertsRouteImport } from './routes/_app/alerts'
import { Route as AppDirectoryIndexRouteImport } from './routes/_app/directory/index'
import { Route as AppDirectoryIdRouteImport } from './routes/_app/directory/$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminRequestsRouteImport } from './routes/_app/admin/requests'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkforceRoute = AppWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeRoute = AppTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => AppRoute,
} as any)
const AppTalentRoute = AppTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPostingsRoute = AppPostingsRouteImport.update({
  id: '/postings',
  path: '/postings',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgRoute = AppOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitoringRoute = AppMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppImportExportRoute = AppImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AppRoute,
} as any)
const AppHiringRoute = AppHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppEngagementRoute = AppEngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttritionRoute = AppAttritionRouteImport.update({
  id: '/attrition',
  path: '/attrition',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryIndexRoute = AppDirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryIdRoute = AppDirectoryIdRouteImport.update({
  id: '/directory/$id',
  path: '/directory/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRequestsRoute = AppAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AppAlertsRoute
  '/attendance': typeof AppAttendanceRoute
  '/attrition': typeof AppAttritionRoute
  '/calendar': typeof AppCalendarRoute
  '/engagement': typeof AppEngagementRoute
  '/expenses': typeof AppExpensesRoute
  '/help': typeof AppHelpRoute
  '/hiring': typeof AppHiringRoute
  '/import-export': typeof AppImportExportRoute
  '/leave': typeof AppLeaveRoute
  '/monitoring': typeof AppMonitoringRoute
  '/onboarding': typeof AppOnboardingRoute
  '/org': typeof AppOrgRoute
  '/overview': typeof AppOverviewRoute
  '/payroll': typeof AppPayrollRoute
  '/postings': typeof AppPostingsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/talent': typeof AppTalentRoute
  '/time': typeof AppTimeRoute
  '/workforce': typeof AppWorkforceRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/directory/$id': typeof AppDirectoryIdRoute
  '/directory/': typeof AppDirectoryIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AppAlertsRoute
  '/attendance': typeof AppAttendanceRoute
  '/attrition': typeof AppAttritionRoute
  '/calendar': typeof AppCalendarRoute
  '/engagement': typeof AppEngagementRoute
  '/expenses': typeof AppExpensesRoute
  '/help': typeof AppHelpRoute
  '/hiring': typeof AppHiringRoute
  '/import-export': typeof AppImportExportRoute
  '/leave': typeof AppLeaveRoute
  '/monitoring': typeof AppMonitoringRoute
  '/onboarding': typeof AppOnboardingRoute
  '/org': typeof AppOrgRoute
  '/overview': typeof AppOverviewRoute
  '/payroll': typeof AppPayrollRoute
  '/postings': typeof AppPostingsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/talent': typeof AppTalentRoute
  '/time': typeof AppTimeRoute
  '/workforce': typeof AppWorkforceRoute
  '/': typeof AppIndexRoute
  '/admin/requests': typeof AppAdminRequestsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/directory/$id': typeof AppDirectoryIdRoute
  '/directory': typeof AppDirectoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/attrition': typeof AppAttritionRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/engagement': typeof AppEngagementRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/hiring': typeof AppHiringRoute
  '/_app/import-export': typeof AppImportExportRoute
  '/_app/leave': typeof AppLeaveRoute
  '/_app/monitoring': typeof AppMonitoringRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/org': typeof AppOrgRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/postings': typeof AppPostingsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/talent': typeof AppTalentRoute
  '/_app/time': typeof AppTimeRoute
  '/_app/workforce': typeof AppWorkforceRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/requests': typeof AppAdminRequestsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/directory/$id': typeof AppDirectoryIdRoute
  '/_app/directory/': typeof AppDirectoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/attendance'
    | '/attrition'
    | '/calendar'
    | '/engagement'
    | '/expenses'
    | '/help'
    | '/hiring'
    | '/import-export'
    | '/leave'
    | '/monitoring'
    | '/onboarding'
    | '/org'
    | '/overview'
    | '/payroll'
    | '/postings'
    | '/profile'
    | '/reports'
    | '/talent'
    | '/time'
    | '/workforce'
    | '/admin/requests'
    | '/admin/users'
    | '/directory/$id'
    | '/directory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/attendance'
    | '/attrition'
    | '/calendar'
    | '/engagement'
    | '/expenses'
    | '/help'
    | '/hiring'
    | '/import-export'
    | '/leave'
    | '/monitoring'
    | '/onboarding'
    | '/org'
    | '/overview'
    | '/payroll'
    | '/postings'
    | '/profile'
    | '/reports'
    | '/talent'
    | '/time'
    | '/workforce'
    | '/'
    | '/admin/requests'
    | '/admin/users'
    | '/directory/$id'
    | '/directory'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_app/alerts'
    | '/_app/attendance'
    | '/_app/attrition'
    | '/_app/calendar'
    | '/_app/engagement'
    | '/_app/expenses'
    | '/_app/help'
    | '/_app/hiring'
    | '/_app/import-export'
    | '/_app/leave'
    | '/_app/monitoring'
    | '/_app/onboarding'
    | '/_app/org'
    | '/_app/overview'
    | '/_app/payroll'
    | '/_app/postings'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/talent'
    | '/_app/time'
    | '/_app/workforce'
    | '/_app/'
    | '/_app/admin/requests'
    | '/_app/admin/users'
    | '/_app/directory/$id'
    | '/_app/directory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workforce': {
      id: '/_app/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AppWorkforceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/time': {
      id: '/_app/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof AppTimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/talent': {
      id: '/_app/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof AppTalentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/postings': {
      id: '/_app/postings'
      path: '/postings'
      fullPath: '/postings'
      preLoaderRoute: typeof AppPostingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/org': {
      id: '/_app/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AppOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitoring': {
      id: '/_app/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leave': {
      id: '/_app/leave'
      path: '/leave'
      fullPath: '/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import-export': {
      id: '/_app/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof AppImportExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hiring': {
      id: '/_app/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof AppHiringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/engagement': {
      id: '/_app/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof AppEngagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attrition': {
      id: '/_app/attrition'
      path: '/attrition'
      fullPath: '/attrition'
      preLoaderRoute: typeof AppAttritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory/': {
      id: '/_app/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof AppDirectoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory/$id': {
      id: '/_app/directory/$id'
      path: '/directory/$id'
      fullPath: '/directory/$id'
      preLoaderRoute: typeof AppDirectoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/requests': {
      id: '/_app/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AppAdminRequestsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppAttritionRoute: typeof AppAttritionRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppEngagementRoute: typeof AppEngagementRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppHiringRoute: typeof AppHiringRoute
  AppImportExportRoute: typeof AppImportExportRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppMonitoringRoute: typeof AppMonitoringRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrgRoute: typeof AppOrgRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPostingsRoute: typeof AppPostingsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppTalentRoute: typeof AppTalentRoute
  AppTimeRoute: typeof AppTimeRoute
  AppWorkforceRoute: typeof AppWorkforceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminRequestsRoute: typeof AppAdminRequestsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppDirectoryIdRoute: typeof AppDirectoryIdRoute
  AppDirectoryIndexRoute: typeof AppDirectoryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppAttritionRoute: AppAttritionRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppEngagementRoute: AppEngagementRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppHelpRoute: AppHelpRoute,
  AppHiringRoute: AppHiringRoute,
  AppImportExportRoute: AppImportExportRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppMonitoringRoute: AppMonitoringRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrgRoute: AppOrgRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPostingsRoute: AppPostingsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppTalentRoute: AppTalentRoute,
  AppTimeRoute: AppTimeRoute,
  AppWorkforceRoute: AppWorkforceRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminRequestsRoute: AppAdminRequestsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppDirectoryIdRoute: AppDirectoryIdRoute,
  AppDirectoryIndexRoute: AppDirectoryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
